"""`EventType` (HLD `10-domain-model.md` §10.2, "EventType").

`str, Enum`; member `NAME == VALUE`. The 28 SPEC §8 members verbatim, then the additive members
allowed by D5 ("at least"): the 21 of I1 plus I3's (HLD 70 §70.7 — `DDS_CARD_STATUS_CHANGED`,
I3 E4a; `RECIPIENTS_RESOLVED`, I3 E2b′). `SPEC_EVENT_TYPES` and `ADDITIVE_EVENT_TYPES` partition
`EventType` and exist so later code (and tests) can assert that partition without re-typing either
list.
"""

from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    # SPEC §8 (28 members, exact, in SPEC order).
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STARTED = "SESSION_STARTED"
    ROLE_STAGE_STARTED = "ROLE_STAGE_STARTED"
    CALL_RINGING = "CALL_RINGING"
    CALL_ANSWERED = "CALL_ANSWERED"
    USER_SPEECH_STARTED = "USER_SPEECH_STARTED"
    USER_SPEECH_ENDED = "USER_SPEECH_ENDED"
    ASR_PARTIAL = "ASR_PARTIAL"
    ASR_FINAL = "ASR_FINAL"
    CALLER_RESPONSE_PLANNED = "CALLER_RESPONSE_PLANNED"
    CALLER_RESPONSE_GENERATED = "CALLER_RESPONSE_GENERATED"
    CALLER_TTS_STARTED = "CALLER_TTS_STARTED"
    CALLER_TTS_ENDED = "CALLER_TTS_ENDED"
    CALLER_UTTERANCE_INTERRUPTED = "CALLER_UTTERANCE_INTERRUPTED"
    CARD_FIELD_CHANGED = "CARD_FIELD_CHANGED"
    SERVICE_SELECTED = "SERVICE_SELECTED"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_RECEIVED = "HANDOFF_RECEIVED"
    DDS_ACKNOWLEDGED = "DDS_ACKNOWLEDGED"
    RESOURCE_SELECTED = "RESOURCE_SELECTED"
    RESOURCE_DISPATCHED = "RESOURCE_DISPATCHED"
    RESOURCE_STATUS_CHANGED = "RESOURCE_STATUS_CHANGED"
    WORLD_EVENT_TRIGGERED = "WORLD_EVENT_TRIGGERED"
    ROLE_STAGE_COMPLETED = "ROLE_STAGE_COMPLETED"
    SCORING_RULE_EVALUATED = "SCORING_RULE_EVALUATED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    MODEL_FALLBACK_USED = "MODEL_FALLBACK_USED"
    MODEL_ERROR = "MODEL_ERROR"

    # Additive per D5 (21 members).
    SESSION_ABORTED = "SESSION_ABORTED"
    STAGE_STATE_CHANGED = "STAGE_STATE_CHANGED"
    ROLE_TRANSITION_STARTED = "ROLE_TRANSITION_STARTED"
    ROLE_TRANSITION_COMPLETED = "ROLE_TRANSITION_COMPLETED"
    SERVICE_DESELECTED = "SERVICE_DESELECTED"
    RESOURCE_DESELECTED = "RESOURCE_DESELECTED"
    DDS_STATUS_UPDATE_SENT = "DDS_STATUS_UPDATE_SENT"
    DDS_INCIDENT_CLOSED = "DDS_INCIDENT_CLOSED"
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_ACKNOWLEDGED = "NOTIFICATION_ACKNOWLEDGED"
    RADIO_MESSAGE_CREATED = "RADIO_MESSAGE_CREATED"
    WORLD_TRUTH_MUTATED = "WORLD_TRUTH_MUTATED"
    CALLER_BELIEF_MUTATED = "CALLER_BELIEF_MUTATED"
    CALLER_EMOTION_CHANGED = "CALLER_EMOTION_CHANGED"
    CALL_ENDED = "CALL_ENDED"
    DIALOGUE_INTERPRETED = "DIALOGUE_INTERPRETED"
    FACT_GATE_EVALUATED = "FACT_GATE_EVALUATED"
    FACTS_DELIVERED = "FACTS_DELIVERED"
    TRANSPORT_DISCONNECTED = "TRANSPORT_DISCONNECTED"
    TRANSPORT_RECONNECTED = "TRANSPORT_RECONNECTED"
    INFERENCE_HEALTH_CHANGED = "INFERENCE_HEALTH_CHANGED"

    # Additive per D5, I3 (HLD 70 §70.7).
    DDS_CARD_STATUS_CHANGED = "DDS_CARD_STATUS_CHANGED"
    """The card's derived status changed (§70.4.6); SIMULATION, deadline-stamped (E4a)."""
    RECIPIENTS_RESOLVED = "RECIPIENTS_RESOLVED"
    """The routing resolver's answer for the card (§70.6.4); SIMULATION, not a card write (E2b′)."""
    DDS_CARD_OPENED = "DDS_CARD_OPENED"
    """A ДДС participant opened the card on one leg (§70.4.2 `receive`); TRAINEE (E5a)."""
    DDS_SERVICE_STATUS_SET = "DDS_SERVICE_STATUS_SET"
    """One leg's `ServiceResponseStatus` moved one step (§70.4.2); TRAINEE or SIMULATION (E5a)."""


SPEC_EVENT_TYPES: frozenset[EventType] = frozenset(
    {
        EventType.SESSION_CREATED,
        EventType.SESSION_STARTED,
        EventType.ROLE_STAGE_STARTED,
        EventType.CALL_RINGING,
        EventType.CALL_ANSWERED,
        EventType.USER_SPEECH_STARTED,
        EventType.USER_SPEECH_ENDED,
        EventType.ASR_PARTIAL,
        EventType.ASR_FINAL,
        EventType.CALLER_RESPONSE_PLANNED,
        EventType.CALLER_RESPONSE_GENERATED,
        EventType.CALLER_TTS_STARTED,
        EventType.CALLER_TTS_ENDED,
        EventType.CALLER_UTTERANCE_INTERRUPTED,
        EventType.CARD_FIELD_CHANGED,
        EventType.SERVICE_SELECTED,
        EventType.HANDOFF_CREATED,
        EventType.HANDOFF_RECEIVED,
        EventType.DDS_ACKNOWLEDGED,
        EventType.RESOURCE_SELECTED,
        EventType.RESOURCE_DISPATCHED,
        EventType.RESOURCE_STATUS_CHANGED,
        EventType.WORLD_EVENT_TRIGGERED,
        EventType.ROLE_STAGE_COMPLETED,
        EventType.SCORING_RULE_EVALUATED,
        EventType.SESSION_COMPLETED,
        EventType.MODEL_FALLBACK_USED,
        EventType.MODEL_ERROR,
    }
)

ADDITIVE_EVENT_TYPES: frozenset[EventType] = frozenset(
    {
        EventType.SESSION_ABORTED,
        EventType.STAGE_STATE_CHANGED,
        EventType.ROLE_TRANSITION_STARTED,
        EventType.ROLE_TRANSITION_COMPLETED,
        EventType.SERVICE_DESELECTED,
        EventType.RESOURCE_DESELECTED,
        EventType.DDS_STATUS_UPDATE_SENT,
        EventType.DDS_INCIDENT_CLOSED,
        EventType.NOTIFICATION_CREATED,
        EventType.NOTIFICATION_ACKNOWLEDGED,
        EventType.RADIO_MESSAGE_CREATED,
        EventType.WORLD_TRUTH_MUTATED,
        EventType.CALLER_BELIEF_MUTATED,
        EventType.CALLER_EMOTION_CHANGED,
        EventType.CALL_ENDED,
        EventType.DIALOGUE_INTERPRETED,
        EventType.FACT_GATE_EVALUATED,
        EventType.FACTS_DELIVERED,
        EventType.TRANSPORT_DISCONNECTED,
        EventType.TRANSPORT_RECONNECTED,
        EventType.INFERENCE_HEALTH_CHANGED,
        EventType.DDS_CARD_STATUS_CHANGED,
        EventType.RECIPIENTS_RESOLVED,
        EventType.DDS_CARD_OPENED,
        EventType.DDS_SERVICE_STATUS_SET,
    }
)

assert frozenset(EventType) == SPEC_EVENT_TYPES | ADDITIVE_EVENT_TYPES
assert not (SPEC_EVENT_TYPES & ADDITIVE_EVENT_TYPES)
