#!/usr/bin/env python3
"""Today's `CARD_FIELDS` → `reference/card-schema/v1.yaml` (HLD 70 §70.5.1, §70.6.1, D17).

`v1.yaml` is the 38 `CARD_FIELDS` of `backend/app/domain/layers/operator_card.py`, field for field
and in order, so the `legacy-r1` pack's card schema is exactly the card every existing session
uses. `v2.yaml` (the organizer card) belongs to E3a and is not produced here.

    uv run python backend/tools/import_card_schema.py           # write v1.yaml + manifest
    uv run python backend/tools/import_card_schema.py --check   # exit 1 when v1.yaml is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

if __package__ in (None, ""):  # run as a script: make `tools.*` importable
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.domain.layers.operator_card import CARD_FIELDS
from tools.import_manifest import REFERENCE_DIR, REPO_ROOT, write_manifest

SCHEMA_ID = "v1"
CARD_SCHEMA_PATH = REFERENCE_DIR / "card-schema" / f"{SCHEMA_ID}.yaml"


def render_card_schema() -> str:
    """The byte-stable `card-schema/v1.yaml` for the current `CARD_FIELDS`."""
    document = {
        "schema_id": SCHEMA_ID,
        "source": "backend/app/domain/layers/operator_card.py CARD_FIELDS",
        "fields": [spec.model_dump(mode="json") for spec in CARD_FIELDS],
    }
    header = (
        "# Generated by backend/tools/import_card_schema.py from CARD_FIELDS — do not edit by "
        "hand.\n"
    )
    return header + yaml.safe_dump(
        document, allow_unicode=True, sort_keys=False, default_flow_style=False, width=1000
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build reference/card-schema/v1.yaml")
    parser.add_argument("--check", action="store_true", help="exit 1 when v1.yaml is stale")
    args = parser.parse_args(argv)
    rendered = render_card_schema()
    if args.check:
        current = CARD_SCHEMA_PATH.read_text(encoding="utf-8") if CARD_SCHEMA_PATH.is_file() else ""
        if current != rendered:
            print(f"{CARD_SCHEMA_PATH} is stale; run import_card_schema.py", file=sys.stderr)
            return 1
        return 0
    CARD_SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    CARD_SCHEMA_PATH.write_text(rendered, encoding="utf-8")
    write_manifest()
    print(f"wrote {CARD_SCHEMA_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
