"""Helpers for driving Alembic and throwaway databases from the integration tests.

Kept out of `conftest.py` so that both the `migrated_engine` fixture and the round-trip /
drift tests use exactly one implementation.
"""

from __future__ import annotations

import argparse
import asyncio
import secrets
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config

#: Repository root, resolved from this file: backend/tests/integration/db/ -> 4 levels up.
REPO_ROOT = Path(__file__).resolve().parents[4]
ALEMBIC_INI = REPO_ROOT / "backend" / "alembic.ini"


def alembic_config(url: str) -> Config:
    """An Alembic `Config` whose `-x url=...` points `env.py` at `url`."""
    config = Config(str(ALEMBIC_INI))
    config.cmd_opts = argparse.Namespace(x=[f"url={url}"])
    return config


def upgrade(url: str, revision: str = "head") -> None:
    command.upgrade(alembic_config(url), revision)


def downgrade(url: str, revision: str = "base") -> None:
    command.downgrade(alembic_config(url), revision)


def check(url: str) -> None:
    """`alembic check` — raises `AutogenerateDiffsDetected` when models and migrations differ."""
    command.check(alembic_config(url))


def replace_database(url: str, database: str) -> str:
    """Return `url` with its database name replaced by `database`."""
    base, _, _ = url.rpartition("/")
    return f"{base}/{database}"


def _dsn(url: str) -> str:
    """Strip the SQLAlchemy driver marker so asyncpg can consume the URL directly."""
    return url.replace("postgresql+asyncpg://", "postgresql://")


async def _execute_on_server(url: str, statement: str) -> None:
    connection = await asyncpg.connect(_dsn(replace_database(url, "postgres")))
    try:
        await connection.execute(statement)
    finally:
        await connection.close()


def random_database_name(prefix: str = "sim_test_") -> str:
    return f"{prefix}{secrets.token_hex(6)}"


def create_database(url: str, name: str) -> None:
    """`CREATE DATABASE name` on the server `url` points at."""
    asyncio.run(_execute_on_server(url, f'CREATE DATABASE "{name}"'))


def drop_database(url: str, name: str) -> None:
    """`DROP DATABASE name` on the server `url` points at, disconnecting any stragglers."""
    asyncio.run(_execute_on_server(url, f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))


def table_names(url: str) -> set[str]:
    """Every table in the `public` schema except Alembic's own version table."""

    async def _query() -> set[str]:
        connection = await asyncpg.connect(_dsn(url))
        try:
            rows = await connection.fetch(
                "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
            )
        finally:
            await connection.close()
        return {row["tablename"] for row in rows} - {"alembic_version"}

    return asyncio.run(_query())
